// botcardpreview writes the browser's copy of the bot-card catalogue: each
// card's identity and the AP innate effects it shows at each tier. Run through
// go generate ./launcher/internal/botcards after editing cards; the test fails
// while the committed file is behind.
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/m-this/tf2-archipelago/gamedata"
	"github.com/m-this/tf2-archipelago/launcher/internal/botcards"
)

var (
	percent     = regexp.MustCompile(`^\+(\d+)% (.+)$`)
	firstNumber = regexp.MustCompile(`\d+`)
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: botcardpreview OUTPUT.ts")
		os.Exit(2)
	}
	out, err := render()
	if err == nil {
		err = os.WriteFile(os.Args[1], []byte(out), 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "botcardpreview: "+err.Error())
		os.Exit(1)
	}
}

func render() (string, error) {
	var b strings.Builder
	b.WriteString("// Generated by go generate ./launcher/internal/botcards. Do not edit.\n\n")
	b.WriteString("export type CardTier = 'common' | 'elite' | 'legendary';\n\n")
	b.WriteString("export interface CardIdentity {\n")
	b.WriteString("  readonly id: string;\n  readonly name: string;\n  readonly classKey: string;\n")
	b.WriteString("  readonly loadoutKey: string;\n  readonly tier: CardTier;\n}\n\n")
	b.WriteString("export const cardIdentities: readonly CardIdentity[] = [\n")
	for _, card := range botcards.Cards {
		fmt.Fprintf(&b, "  { id: %q, name: %q, classKey: %q, loadoutKey: %q, tier: %q },\n",
			card.ID, card.Name, card.Class, card.Loadout, card.Tier)
	}
	b.WriteString("];\n\n")
	b.WriteString("export const cardInnates: Readonly<Record<string, Readonly<Record<CardTier, readonly string[]>>>> = {\n")
	for _, card := range botcards.Cards {
		fmt.Fprintf(&b, "  %q: {\n", card.ID)
		for _, tier := range []botcards.Tier{botcards.Common, botcards.Elite, botcards.Legendary} {
			fmt.Fprintf(&b, "    %s: [", tier)
			for index, id := range botcards.BuffsFor(card, tier) {
				buff, ok := gamedata.WeaponBuffByID(id)
				if !ok {
					return "", fmt.Errorf("card %q has unknown buff %d", card.ID, id)
				}
				if index > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%q", display(buff.Description, tier.Stacks()))
			}
			b.WriteString("],\n")
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	return b.String(), nil
}

func display(description string, stacks int) string {
	if parts := percent.FindStringSubmatch(description); parts != nil {
		n, _ := strconv.Atoi(parts[1])
		label := parts[2]
		first, width := utf8.DecodeRuneInString(label)
		return strings.ToUpper(string(first)) + label[width:] + fmt.Sprintf(" +%d%%", n*stacks)
	}
	return firstNumber.ReplaceAllStringFunc(description, func(number string) string {
		n, _ := strconv.Atoi(number)
		return strconv.Itoa(n * stacks)
	})
}
