// botcardpreview writes the small browser table of actual AP innate effects.
// Run through go generate ./launcher/internal/botcards after editing cards.
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/m-this/tf2-archipelago/gamedata"
	"github.com/m-this/tf2-archipelago/launcher/internal/botcards"
)

var percent = regexp.MustCompile(`^\+(\d+)% (.+)$`)
var firstNumber = regexp.MustCompile(`\d+`)

func main() {
	if len(os.Args) != 2 {
		panic("usage: botcardpreview OUTPUT.ts")
	}
	var b strings.Builder
	b.WriteString("// Generated by go generate ./launcher/internal/botcards. Do not edit.\n")
	b.WriteString("export const cardInnates: Record<string, Record<string, readonly string[]>> = {\n")
	for _, card := range botcards.Cards {
		fmt.Fprintf(&b, "  %q: {\n", card.ID)
		for _, tier := range []botcards.Tier{botcards.Common, botcards.Elite, botcards.Legendary} {
			fmt.Fprintf(&b, "    %q: [", tier)
			for index, id := range botcards.BuffsFor(card, tier) {
				buff, ok := gamedata.WeaponBuffByID(id)
				if !ok {
					panic(fmt.Sprintf("card %q has unknown buff %d", card.ID, id))
				}
				if index > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%q", display(buff.Description, tier.Stacks()))
			}
			b.WriteString("],\n")
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func display(description string, stacks int) string {
	if parts := percent.FindStringSubmatch(description); parts != nil {
		n, _ := strconv.Atoi(parts[1])
		label := parts[2]
		first, width := utf8.DecodeRuneInString(label)
		return strings.ToUpper(string(first)) + label[width:] + fmt.Sprintf(" +%d%%", n*stacks)
	}
	return firstNumber.ReplaceAllStringFunc(description, func(number string) string {
		n, _ := strconv.Atoi(number)
		return strconv.Itoa(n * stacks)
	})
}
