"""Reader for the tables generated by ``gamedata/``.

The Go package owns every Mann vs Machine fact and id and exports them as the
JSON under ``data/``; see ADR 0001.

``pkgutil.get_data`` rather than ``open``: a packaged ``.apworld`` is a zip and
there is no file to open.
"""

import json
import pkgutil
from dataclasses import dataclass

# A version mismatch is a hard stop: half-reading a moved table makes a seed wrong undetectably.
FORMAT_VERSION = 4


class DataFormatError(Exception):
    pass


def _load(name: str) -> dict:
    body = pkgutil.get_data(__name__, f"data/{name}")
    if body is None:
        raise DataFormatError(f"data/{name} is missing from the apworld")
    document = json.loads(body)
    version = document.get("format_version")
    if version != FORMAT_VERSION:
        raise DataFormatError(
            f"data/{name} is format version {version!r}, this apworld reads {FORMAT_VERSION}"
        )
    return document


@dataclass(frozen=True, slots=True)
class Location:
    """``kind`` is the objective the plugin reports for this check."""

    id: int
    name: str
    kind: str
    wave: int


@dataclass(frozen=True, slots=True)
class Mission:
    """``has_tank`` and ``has_giant`` are why those checks exist for a mission."""

    id: int
    pop_file: str
    name: str
    map_id: int
    difficulty: str
    waves: int
    has_tank: bool
    has_giant: bool
    community: bool
    playable: bool
    requires: str
    locations: tuple[Location, ...]

    def seedable_with(self, server_mods: set[str] | frozenset[str]) -> bool:
        """Whether a server loading these mods can play the mission."""
        return self.playable or (self.requires in SERVER_MOD_KEYS and self.requires in server_mods)


@dataclass(frozen=True, slots=True)
class Item:
    id: int
    name: str
    kind: str
    classification: str
    count: int
    mission_id: int
    class_id: int
    credits: int
    weapon_buff_id: int
    stackable: bool
    eligible: bool


def _read_missions() -> tuple[Mission, ...]:
    return tuple(
        Mission(
            id=entry["id"],
            pop_file=entry["pop_file"],
            name=entry["name"],
            map_id=entry["map_id"],
            difficulty=entry["difficulty"],
            waves=entry["waves"],
            has_tank=entry["has_tank"],
            has_giant=entry["has_giant"],
            community=entry["community"],
            playable=entry["playable"],
            requires=entry.get("requires", ""),
            locations=tuple(
                Location(
                    id=location["id"],
                    name=location["name"],
                    kind=location["kind"],
                    wave=location.get("wave", 0),
                )
                for location in entry["locations"]
            ),
        )
        for entry in _load("missions.json")["missions"]
    )


def _read_items() -> tuple[Item, ...]:
    return tuple(
        Item(
            id=entry["id"],
            name=entry["name"],
            kind=entry["kind"],
            classification=entry["classification"],
            count=entry["count"],
            mission_id=entry.get("mission_id", 0),
            class_id=entry.get("class_id", 0),
            credits=entry.get("credits", 0),
            weapon_buff_id=entry.get("weapon_buff_id", 0),
            stackable=entry.get("stackable", False),
            eligible=entry.get("eligible", False),
        )
        for entry in _load("items.json")["items"]
    )


_meta = _load("meta.json")

GAME: str = _meta["game"]
BASE_ID: int = _meta["base_id"]

# Easiest tier first: the order is the ladder difficulty_pool walks.
DIFFICULTIES: tuple[str, ...] = tuple(tier["key"] for tier in _meta["difficulties"])
MAP_NAMES: dict[int, str] = {entry["id"]: entry["name"] for entry in _meta["maps"]}
SERVER_MOD_KEYS: frozenset[str] = frozenset(mod["key"] for mod in _meta["server_mods"])

MISSIONS: tuple[Mission, ...] = _read_missions()
ITEMS: tuple[Item, ...] = _read_items()

LOCATION_NAME_TO_ID: dict[str, int] = {
    location.name: location.id for mission in MISSIONS for location in mission.locations
}
ITEM_NAME_TO_ID: dict[str, int] = {item.name: item.id for item in ITEMS}
ITEMS_BY_NAME: dict[str, Item] = {item.name: item for item in ITEMS}

TICKET_NAMES: dict[int, str] = {
    item.mission_id: item.name for item in ITEMS if item.kind == "mission_ticket"
}
CLASS_NAMES: tuple[str, ...] = tuple(item.name for item in ITEMS if item.kind == "class")

# "Scout" is what a player writes in a YAML; "Class: Scout" is what the item is
# called. The link is the class id, not the shape of the name.
_MERC_NAMES: dict[int, str] = {entry["id"]: entry["name"] for entry in _meta["classes"]}
CLASS_ITEM_BY_MERC: dict[str, str] = {
    _MERC_NAMES[item.class_id]: item.name for item in ITEMS if item.kind == "class"
}
if len(CLASS_ITEM_BY_MERC) != len(CLASS_NAMES):
    raise DataFormatError("a class item names a class the meta export does not have")

# Every mission some server can play: the stock ones and those a cataloged
# mod unlocks. A YAML may name any of them; the server_mods option decides
# which are drawn.
MISSION_NAMES: frozenset[str] = frozenset(
    mission.name for mission in MISSIONS if mission.seedable_with(SERVER_MOD_KEYS)
)
FILLER_NAMES: tuple[str, ...] = tuple(
    item.name for item in ITEMS if item.classification == "filler"
)
WEAPON_BUFF_NAMES: tuple[str, ...] = tuple(
    item.name for item in ITEMS if item.kind == "weapon_buff" and item.eligible
)
STACKABLE_WEAPON_BUFF_NAMES: frozenset[str] = frozenset(
    item.name for item in ITEMS if item.kind == "weapon_buff" and item.eligible and item.stackable
)
TRAP_NAMES: tuple[str, ...] = tuple(item.name for item in ITEMS if item.kind == "trap")
if not TRAP_NAMES:
    raise DataFormatError("the export has no trap items")

_weapon_slot_items = [item for item in ITEMS if item.kind == "weapon_slot"]
if len(_weapon_slot_items) != 1:
    raise DataFormatError("expected exactly one progressive weapon slot item")

# One item name, several copies: copy n unlocks the nth loadout slot.
PROGRESSIVE_WEAPON_SLOT: str = _weapon_slot_items[0].name
WEAPON_SLOT_COUNT: int = _weapon_slot_items[0].count

ITEM_NAME_GROUPS: dict[str, set[str]] = {
    "Classes": set(CLASS_NAMES),
    "Mission Tickets": set(TICKET_NAMES.values()),
    "Weapon Buffs": set(WEAPON_BUFF_NAMES),
    "Traps": set(TRAP_NAMES),
}
