"""Reader for the tables generated by ``gamedata/``.

The Go package owns every Mann vs Machine fact and id and exports them as the
JSON under ``data/``; see ADR 0001.

``pkgutil.get_data`` rather than ``open``: a packaged ``.apworld`` is a zip and
there is no file to open.
"""

import json
import pkgutil
from dataclasses import dataclass

# A version mismatch is a hard stop: half-reading a moved table makes a seed wrong undetectably.
FORMAT_VERSION = 1


class DataFormatError(Exception):
    pass


def _load(name: str) -> dict:
    body = pkgutil.get_data(__name__, f"data/{name}")
    if body is None:
        raise DataFormatError(f"data/{name} is missing from the apworld")
    document = json.loads(body)
    version = document.get("format_version")
    if version != FORMAT_VERSION:
        raise DataFormatError(
            f"data/{name} is format version {version!r}, this apworld reads {FORMAT_VERSION}"
        )
    return document


@dataclass(frozen=True, slots=True)
class Location:
    """``kind`` is the objective the plugin reports for this check."""

    id: int
    name: str
    kind: str
    wave: int


@dataclass(frozen=True, slots=True)
class Mission:
    id: int
    pop_file: str
    name: str
    map_id: int
    difficulty: str
    waves: int
    locations: tuple[Location, ...]


@dataclass(frozen=True, slots=True)
class Item:
    id: int
    name: str
    kind: str
    classification: str
    count: int
    mission_id: int
    class_id: int
    credits: int


def _read_missions() -> tuple[Mission, ...]:
    return tuple(
        Mission(
            id=entry["id"],
            pop_file=entry["pop_file"],
            name=entry["name"],
            map_id=entry["map_id"],
            difficulty=entry["difficulty"],
            waves=entry["waves"],
            locations=tuple(
                Location(
                    id=location["id"],
                    name=location["name"],
                    kind=location["kind"],
                    wave=location.get("wave", 0),
                )
                for location in entry["locations"]
            ),
        )
        for entry in _load("missions.json")["missions"]
    )


def _read_items() -> tuple[Item, ...]:
    return tuple(
        Item(
            id=entry["id"],
            name=entry["name"],
            kind=entry["kind"],
            classification=entry["classification"],
            count=entry["count"],
            mission_id=entry.get("mission_id", 0),
            class_id=entry.get("class_id", 0),
            credits=entry.get("credits", 0),
        )
        for entry in _load("items.json")["items"]
    )


_meta = _load("meta.json")

GAME: str = _meta["game"]
BASE_ID: int = _meta["base_id"]

# Easiest tier first: the order is the ladder difficulty_pool walks.
DIFFICULTIES: tuple[str, ...] = tuple(tier["key"] for tier in _meta["difficulties"])
MAP_NAMES: dict[int, str] = {entry["id"]: entry["name"] for entry in _meta["maps"]}

MISSIONS: tuple[Mission, ...] = _read_missions()
ITEMS: tuple[Item, ...] = _read_items()

LOCATION_NAME_TO_ID: dict[str, int] = {
    location.name: location.id for mission in MISSIONS for location in mission.locations
}
ITEM_NAME_TO_ID: dict[str, int] = {item.name: item.id for item in ITEMS}
ITEMS_BY_NAME: dict[str, Item] = {item.name: item for item in ITEMS}

TICKET_NAMES: dict[int, str] = {
    item.mission_id: item.name for item in ITEMS if item.kind == "mission_ticket"
}
CLASS_NAMES: tuple[str, ...] = tuple(item.name for item in ITEMS if item.kind == "class")
FILLER_NAMES: tuple[str, ...] = tuple(
    item.name for item in ITEMS if item.classification == "filler"
)

_weapon_slot_items = [item for item in ITEMS if item.kind == "weapon_slot"]
if len(_weapon_slot_items) != 1:
    raise DataFormatError("expected exactly one progressive weapon slot item")

# One item name, several copies: copy n unlocks the nth loadout slot.
PROGRESSIVE_WEAPON_SLOT: str = _weapon_slot_items[0].name
WEAPON_SLOT_COUNT: int = _weapon_slot_items[0].count

ITEM_NAME_GROUPS: dict[str, set[str]] = {
    "Classes": set(CLASS_NAMES),
    "Mission Tickets": set(TICKET_NAMES.values()),
}
