package gamedata

// WeaponEffects is the first-pass positive gameplay attribute catalog. Names
// are the schema names consumed by TF2Attributes. Percentage increments are
// deliberately linear: two +10% damage items produce 1.20, not 1.21.
var WeaponEffects = []WeaponEffect{
	{1, "damage", "damage bonus", 0.10, BuffPercentage, "+10% damage"},
	{2, "fire-rate", "fire rate bonus", -0.10, BuffPercentage, "+10% firing speed"},
	{3, "reload-rate", "faster reload rate", -0.15, BuffPercentage, "+15% reload speed"},
	{4, "clip-size", "clip size bonus", 0.25, BuffPercentage, "+25% clip size"},
	{5, "projectile-speed", "Projectile speed increased", 0.15, BuffPercentage, "+15% projectile speed"},
	{6, "projectile-count", "bullets per shot bonus", 1.00, BuffPercentage, "+1 projectile or pellet per shot"},
	{7, "heal-on-kill", "heal on kill", 15.00, BuffAdd, "+15 health on kill"},
	{8, "crits-on-kill", "critboost on kill", 2.00, BuffAdd, "2 seconds of critical hits on kill"},
	{9, "bleed", "bleeding duration", 3.00, BuffAdd, "inflicts 3 seconds of bleed"},
	{10, "ignite", "Set DamageType Ignite", 1.00, BuffToggle, "ignites on hit"},
	{11, "afterburn-damage", "weapon burn dmg increased", 0.25, BuffPercentage, "+25% afterburn damage"},
	{12, "afterburn-duration", "weapon burn time increased", 0.20, BuffPercentage, "+20% afterburn duration"},
	{13, "airborne-crits", "mod crit while airborne", 1.00, BuffToggle, "critical hits while airborne"},
	{14, "airborne-minicrits", "mod mini-crit airborne", 1.00, BuffToggle, "mini-crits airborne targets"},
	{15, "mad-milk", "mad milk syringes", 1.00, BuffToggle, "applies Mad Milk on hit"},
	{16, "gasoline", "explode_on_ignite", 1.00, BuffToggle, "gas-covered enemies explode on ignite"},
	{17, "mark-for-death", "mark for death", 1.00, BuffToggle, "marks victims for death"},
	{18, "explosive-shots", "explosive sniper shot", 1.00, BuffAdd, "+1 explosive-shot level"},
	{19, "projectile-penetration", "projectile penetration", 1.00, BuffToggle, "projectiles penetrate players"},
	{20, "destroy-projectiles", "attack projectiles", 1.00, BuffAdd, "+1 projectile-destruction level"},
	{21, "knockback", "damage causes airblast", 1.00, BuffToggle, "hits knock enemies back"},
	{22, "heal-on-hit", "heal on hit for rapidfire", 2.00, BuffAdd, "+2 health on hit"},
	{23, "speed-on-kill", "speed_boost_on_kill", 1.00, BuffToggle, "speed boost on kill"},
	{24, "max-ammo", "maxammo primary increased", 0.25, BuffPercentage, "+25% reserve ammo"},
	{25, "move-speed", "major move speed bonus", 0.05, BuffPercentage, "+5% movement speed while active"},
	{26, "jump-height", "increased jump height from weapon", 0.15, BuffPercentage, "+15% jump height"},
	{27, "healing", "heal rate bonus", 0.10, BuffPercentage, "+10% healing"},
	{28, "banner-duration", "increase buff duration", 0.20, BuffPercentage, "+20% banner duration"},
	{29, "uber-rate", "ubercharge rate bonus", 0.10, BuffPercentage, "+10% ÜberCharge rate"},
	{30, "airblast-power", "airblast pushback scale", 0.25, BuffPercentage, "+25% airblast force"},
	{31, "airblast-rate", "mult airblast refire time", -0.10, BuffPercentage, "+10% airblast speed"},
	{32, "armor-piercing", "armor piercing", 25.00, BuffAdd, "+25% armor piercing"},
	{33, "cloak-on-hit", "add cloak on hit", 5.00, BuffAdd, "+5 cloak on hit"},
	{34, "cloak-on-kill", "add cloak on kill", 15.00, BuffAdd, "+15 cloak on kill"},
	{35, "building-health", "engy building health bonus", 0.25, BuffPercentage, "+25% building health"},
	{36, "sentry-fire-rate", "engy sentry fire rate increased", -0.10, BuffPercentage, "+10% sentry firing speed"},
	{37, "disposable-sentry", "engy disposable sentries", 1.00, BuffAdd, "+1 disposable mini-sentry"},
	{38, "metal-regen", "metal regen", 5.00, BuffAdd, "+5 metal regenerated"},
	{39, "max-health", "max health additive bonus", 15.00, BuffAdd, "+15 max health while active"},
	{40, "uber-on-hit", "add uber charge on hit", 0.05, BuffAdd, "+5% ÜberCharge on hit"},
	{41, "crits-vs-burning", "crit vs burning players", 1.00, BuffToggle, "critical hits against burning enemies"},
	{42, "back-crits", "mod flamethrower back crit", 1.00, BuffToggle, "critical hits from behind"},
	{43, "sniper-charge", "sniper charge per sec", 0.15, BuffPercentage, "+15% charge rate"},
	// Keep the historical key so existing Archipelago item IDs remain stable.
	{44, "pellet-count", "melee range multiplier", 0.15, BuffPercentage, "+15% melee range"},
	{45, "aiming-speed", "aiming movespeed increased", 0.15, BuffPercentage, "+15% movement speed while aiming"},
	{46, "secondary-ammo", "maxammo secondary increased", 0.25, BuffPercentage, "+25% secondary reserve ammo"},
	{47, "max-metal", "maxammo metal increased", 0.25, BuffPercentage, "+25% max metal"},
	{48, "cloak-duration", "cloak consume rate decreased", -0.15, BuffPercentage, "+15% cloak duration"},
	{49, "cloak-regen", "cloak regen rate increased", 0.15, BuffPercentage, "+15% cloak regeneration"},
	{50, "max-stickies", "max pipebombs increased", 1.00, BuffAdd, "+1 stickybomb out"},
	{51, "construction-rate", "Construction rate increased", 0.25, BuffPercentage, "+25% construction rate"},
	{52, "repair-rate", "Repair rate increased", 0.25, BuffPercentage, "+25% repair rate"},
	{53, "blast-radius", "Blast radius increased", 0.15, BuffPercentage, "+15% explosion radius"},
	{54, "projectile-range", "Projectile range increased", 0.15, BuffPercentage, "+15% projectile range"},
	{55, "accuracy", "weapon spread bonus", -0.10, BuffPercentage, "+10% accuracy"},
	{56, "health-packs", "health from packs increased", 0.25, BuffPercentage, "+25% health from packs"},
	{57, "ammo-regen", "ammo regen", 0.05, BuffAdd, "+5% ammo regeneration"},
	{58, "flame-size", "flame size bonus", 0.15, BuffPercentage, "+15% flame size"},
	{59, "flame-range", "flame life bonus", 0.15, BuffPercentage, "+15% flame range"},
	{60, "charged-airblast", "charged airblast", 1.00, BuffToggle, "airblast can be charged"},
	{61, "jarate", "jarate duration", 2.00, BuffAdd, "+2 seconds of Jarate on scoped hit"},
	{62, "minicrits-to-crits", "minicrits become crits", 1.00, BuffToggle, "mini-crits become critical hits"},
	{63, "no-self-blast", "no self blast dmg", 1.00, BuffToggle, "no self-inflicted blast damage"},
	{64, "drop-health-pack", "drop health pack on kill", 1.00, BuffToggle, "drops a health pack on kill"},
	{65, "slow-on-hit", "slow enemy on hit", 1.00, BuffToggle, "slows enemies on hit"},
	{66, "gesture-speed", "gesture speed increase", 0.50, BuffPercentage, "+50% gesture and consumable speed"},
	{67, "active-health-regen", "active health regen", 2.00, BuffAdd, "+2 health regenerated while active"},
	{68, "deploy-speed", "deploy time decreased", -0.20, BuffPercentage, "+20% deploy speed"},
	{69, "meter-recharge", "effect bar recharge rate increased", -0.20, BuffPercentage, "+20% meter recharge speed"},
	{70, "ammo-on-hit", "add onhit addammo", 1.00, BuffAdd, "+1 ammo on hit"},
	{71, "minicrits-on-kill", "minicritboost on kill", 3.00, BuffAdd, "3 seconds of mini-crits on kill"},
	{72, "healing-received", "healing received bonus", 0.10, BuffPercentage, "+10% healing received while active"},
	{73, "rocket-jump-protection", "rocket jump damage reduction", -0.25, BuffPercentage, "+25% rocket-jump damage resistance"},
	{74, "self-blast-force", "self dmg push force increased", 0.15, BuffPercentage, "+15% self-damage launch force"},
	{75, "spinup-speed", "minigun spinup time decreased", -0.15, BuffPercentage, "+15% minigun spin-up speed"},
	{76, "airblast-cost", "airblast cost decreased", -0.15, BuffPercentage, "-15% airblast ammo cost"},
	{77, "uber-duration", "uber duration bonus", 1.00, BuffAdd, "+1 second of ÜberCharge duration"},
	{78, "reveal-cloaked", "reveal cloaked victim on hit", 1.00, BuffToggle, "reveals cloaked victims on hit"},
	{79, "reveal-disguised", "reveal disguised victim on hit", 1.00, BuffToggle, "reveals disguised victims on hit"},
	{80, "speed-on-hit", "speed_boost_on_hit_enemy", 1.00, BuffToggle, "speed boost on hitting an enemy"},
}
