package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/m-this/tf2-archipelago/gamedata"
)

func quoted(value string) string { return strconv.QuoteToASCII(value) }

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: pluginbuffs <output.inc>")
		os.Exit(2)
	}
	if err := os.WriteFile(os.Args[1], []byte(generate()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() string {
	var out strings.Builder
	out.WriteString("// Code generated by gamedata/cmd/pluginbuffs; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "#define WeaponCount %d\n", len(gamedata.BuffWeapons))
	fmt.Fprintf(&out, "#define WeaponEffectCount %d\n\n", len(gamedata.WeaponEffects))

	out.WriteString("char g_WeaponBuffKeys[][] = {\n")
	for _, buff := range gamedata.WeaponBuffs {
		fmt.Fprintf(&out, "    %s,\n", quoted(buff.Key))
	}
	out.WriteString("};\n\nint g_WeaponBuffWeapon[] = {\n")
	for _, buff := range gamedata.WeaponBuffs {
		fmt.Fprintf(&out, "    %d,\n", buff.ApplyWeaponID-1)
	}
	out.WriteString("};\n\nint g_WeaponBuffEffect[] = {\n")
	for _, buff := range gamedata.WeaponBuffs {
		fmt.Fprintf(&out, "    %d,\n", buff.EffectID-1)
	}
	out.WriteString("};\n\n")

	writeStrings := func(name string, values []string) {
		fmt.Fprintf(&out, "char %s[][] = {\n", name)
		for _, value := range values {
			fmt.Fprintf(&out, "    %s,\n", quoted(value))
		}
		out.WriteString("};\n\n")
	}
	weaponNames := make([]string, 0, len(gamedata.BuffWeapons))
	for _, weapon := range gamedata.BuffWeapons {
		weaponNames = append(weaponNames, weapon.Name)
	}
	writeStrings("g_WeaponNames", weaponNames)
	attributes := make([]string, 0, len(gamedata.WeaponEffects))
	descriptions := make([]string, 0, len(gamedata.WeaponEffects))
	effectKeys := make([]string, 0, len(gamedata.WeaponEffects))
	for _, effect := range gamedata.WeaponEffects {
		effectKeys = append(effectKeys, effect.Key)
		attributes = append(attributes, effect.Attribute)
		descriptions = append(descriptions, effect.Description)
	}
	writeStrings("g_WeaponEffectKeys", effectKeys)
	writeStrings("g_WeaponEffectAttributes", attributes)
	writeStrings("g_WeaponEffectDescriptions", descriptions)

	out.WriteString("float g_WeaponEffectIncrements[] = {\n")
	for _, effect := range gamedata.WeaponEffects {
		fmt.Fprintf(&out, "    %.2f,\n", effect.Increment)
	}
	out.WriteString("};\n\nint g_WeaponEffectModes[] = {\n")
	for _, effect := range gamedata.WeaponEffects {
		fmt.Fprintf(&out, "    %d,\n", effect.Mode)
	}
	out.WriteString("};\n\n// Item definition index, then zero-based weapon index.\n")
	out.WriteString("int g_WeaponByDefinition[][2] = {\n")
	for index, weapon := range gamedata.BuffWeapons {
		if weapon.ApplyID != weapon.ID {
			continue
		}
		for _, definition := range weapon.DefIndexes {
			fmt.Fprintf(&out, "    { %d, %d },\n", definition, index)
		}
	}
	out.WriteString("};\n")
	return out.String()
}
