package apclient

import (
	"fmt"
	"slices"

	"git-ssh.croque.top/mathis/tf2-archipelago/gamedata"
)

// validate rejects slot data the bridge cannot act on. A seed generated by an
// apworld the bridge does not understand is not something to muddle through:
// the ids in it may not mean what this binary thinks they mean.
func (s SlotData) validate() error {
	if s.FormatVersion != gamedata.FormatVersion {
		return fmt.Errorf(
			"seed was generated with data format version %d, this bridge holds %d",
			s.FormatVersion, gamedata.FormatVersion,
		)
	}
	if len(s.Missions) == 0 {
		return fmt.Errorf("seed has no missions")
	}
	for _, popFile := range s.Missions {
		if _, known := gamedata.MissionByPopFile(popFile); !known {
			return fmt.Errorf("seed uses mission %q, which is not in the tables", popFile)
		}
	}
	switch s.Goal {
	case "final_boss":
		if _, known := gamedata.MissionByPopFile(s.GoalMission); !known {
			return fmt.Errorf("goal mission %q is not in the tables", s.GoalMission)
		}
	case "missionsanity":
		if s.MissionsanityTarget < 1 || s.MissionsanityTarget > len(s.Missions) {
			return fmt.Errorf(
				"missionsanity wants %d of %d missions",
				s.MissionsanityTarget, len(s.Missions),
			)
		}
	default:
		return fmt.Errorf("unknown goal %q", s.Goal)
	}
	return nil
}

// goalReached reads the win condition off the checks the plugin has reported.
// The bridge does not track missions separately: a mission is cleared exactly
// when its clear location has been checked.
func (s SlotData) goalReached(checks []int64) bool {
	switch s.Goal {
	case "final_boss":
		mission, known := gamedata.MissionByPopFile(s.GoalMission)
		return known && slices.Contains(checks, mission.ClearLocationID())

	case "missionsanity":
		cleared := 0
		for _, popFile := range s.Missions {
			mission, known := gamedata.MissionByPopFile(popFile)
			if known && slices.Contains(checks, mission.ClearLocationID()) {
				cleared++
			}
		}
		return cleared >= s.MissionsanityTarget

	default:
		return false
	}
}
