// Generated by go generate ./launcher/internal/botcards. Do not edit.

export type CardTier = 'common' | 'elite' | 'legendary';

export interface CardIdentity {
  readonly id: string;
  readonly name: string;
  readonly classKey: string;
  readonly loadoutKey: string;
  readonly tier: CardTier;
}

export const cardIdentities: readonly CardIdentity[] = [
  { id: "stock-scout", name: "Chucklenuts", classKey: "scout", loadoutKey: "stock", tier: "common" },
  { id: "stock-soldier", name: "Maggot", classKey: "soldier", loadoutKey: "stock", tier: "common" },
  { id: "stock-pyro", name: "BeepBeepBoop", classKey: "pyro", loadoutKey: "stock", tier: "common" },
  { id: "stock-demoman", name: "Kaboom!", classKey: "demoman", loadoutKey: "stock", tier: "common" },
  { id: "stock-heavy", name: "Nom Nom Nom", classKey: "heavyweapons", loadoutKey: "stock", tier: "common" },
  { id: "stock-engineer", name: "MoreGun", classKey: "engineer", loadoutKey: "stock", tier: "common" },
  { id: "stock-medic", name: "Archimedes!", classKey: "medic", loadoutKey: "stock", tier: "common" },
  { id: "stock-sniper", name: "A Professional With Standards", classKey: "sniper", loadoutKey: "stock", tier: "common" },
  { id: "stock-spy", name: "Gentlemanne of Leisure", classKey: "spy", loadoutKey: "stock", tier: "common" },
  { id: "credit-to-team", name: "CreditToTeam", classKey: "scout", loadoutKey: "milk", tier: "common" },
  { id: "screamin-eagles", name: "Screamin' Eagles", classKey: "soldier", loadoutKey: "beggar", tier: "elite" },
  { id: "ivan", name: "IvanTheSpaceBiker", classKey: "heavyweapons", loadoutKey: "brass", tier: "elite" },
  { id: "herr-doktor", name: "Herr Doktor", classKey: "medic", loadoutKey: "kritz", tier: "legendary" },
  { id: "chell", name: "Chell", classKey: "engineer", loadoutKey: "ranger", tier: "common" },
  { id: "mentlegen", name: "Mentlegen", classKey: "spy", loadoutKey: "diamondback", tier: "legendary" },
];

export const cardInnates: Readonly<Record<string, Readonly<Record<CardTier, readonly string[]>>>> = {
  "stock-scout": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "Firing speed +20%"],
    legendary: ["Damage +30%", "Firing speed +30%", "Reload speed +45%"],
  },
  "stock-soldier": {
    common: ["+15 health on kill"],
    elite: ["+30 health on kill", "Damage +20%"],
    legendary: ["+45 health on kill", "Damage +30%", "Firing speed +30%"],
  },
  "stock-pyro": {
    common: ["inflicts 3 seconds of bleed"],
    elite: ["inflicts 6 seconds of bleed", "Damage +20%"],
    legendary: ["inflicts 9 seconds of bleed", "Damage +30%", "+45 health on kill"],
  },
  "stock-demoman": {
    common: ["Projectile speed +15%"],
    elite: ["Projectile speed +30%", "Damage +20%"],
    legendary: ["Projectile speed +45%", "Damage +30%", "Firing speed +30%"],
  },
  "stock-heavy": {
    common: ["+15 health on kill"],
    elite: ["+30 health on kill", "Damage +20%"],
    legendary: ["+45 health on kill", "Damage +30%", "Firing speed +30%"],
  },
  "stock-engineer": {
    common: ["inflicts 3 seconds of bleed"],
    elite: ["inflicts 6 seconds of bleed", "Damage +20%"],
    legendary: ["inflicts 9 seconds of bleed", "Damage +30%", "Firing speed +30%"],
  },
  "stock-medic": {
    common: ["inflicts 3 seconds of bleed"],
    elite: ["inflicts 6 seconds of bleed", "Damage +20%"],
    legendary: ["inflicts 9 seconds of bleed", "Damage +30%", "Firing speed +30%"],
  },
  "stock-sniper": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "+2 projectile or pellet per shot"],
    legendary: ["Damage +30%", "+3 projectile or pellet per shot", "+45 health on kill"],
  },
  "stock-spy": {
    common: ["inflicts 3 seconds of bleed"],
    elite: ["inflicts 6 seconds of bleed", "Damage +20%"],
    legendary: ["inflicts 9 seconds of bleed", "Damage +30%", "Firing speed +30%"],
  },
  "credit-to-team": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "Firing speed +20%"],
    legendary: ["Damage +30%", "Firing speed +30%", "+45 health on kill"],
  },
  "screamin-eagles": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "Firing speed +20%"],
    legendary: ["Damage +30%", "Firing speed +30%", "+45 health on kill"],
  },
  "ivan": {
    common: ["Firing speed +10%"],
    elite: ["Firing speed +20%", "Clip size +50%"],
    legendary: ["Firing speed +30%", "Clip size +75%", "Damage +30%"],
  },
  "herr-doktor": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "ÜberCharge rate +20%"],
    legendary: ["Damage +30%", "ÜberCharge rate +30%", "Firing speed +30%"],
  },
  "chell": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "Firing speed +20%"],
    legendary: ["Damage +30%", "Firing speed +30%", "+45 health on kill"],
  },
  "mentlegen": {
    common: ["Damage +10%"],
    elite: ["Damage +20%", "Firing speed +20%"],
    legendary: ["Damage +30%", "Firing speed +30%", "Armor piercing +75%"],
  },
};
