// Generated by go generate ./launcher/internal/botcards. Do not edit.
export const cardInnates: Record<string, Record<string, readonly string[]>> = {
  'stock-scout': {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'Firing speed +20%'],
    legendary: ['Damage +30%', 'Firing speed +30%', 'Reload speed +45%'],
  },
  'stock-soldier': {
    common: ['+15 health on kill'],
    elite: ['+30 health on kill', 'Damage +20%'],
    legendary: ['+45 health on kill', 'Damage +30%', 'Firing speed +30%'],
  },
  'stock-pyro': {
    common: ['inflicts 3 seconds of bleed'],
    elite: ['inflicts 6 seconds of bleed', 'Damage +20%'],
    legendary: ['inflicts 9 seconds of bleed', 'Damage +30%', '+45 health on kill'],
  },
  'stock-demoman': {
    common: ['Projectile speed +15%'],
    elite: ['Projectile speed +30%', 'Damage +20%'],
    legendary: ['Projectile speed +45%', 'Damage +30%', 'Firing speed +30%'],
  },
  'stock-heavy': {
    common: ['+15 health on kill'],
    elite: ['+30 health on kill', 'Damage +20%'],
    legendary: ['+45 health on kill', 'Damage +30%', 'Firing speed +30%'],
  },
  'stock-engineer': {
    common: ['inflicts 3 seconds of bleed'],
    elite: ['inflicts 6 seconds of bleed', 'Damage +20%'],
    legendary: ['inflicts 9 seconds of bleed', 'Damage +30%', 'Firing speed +30%'],
  },
  'stock-medic': {
    common: ['inflicts 3 seconds of bleed'],
    elite: ['inflicts 6 seconds of bleed', 'Damage +20%'],
    legendary: ['inflicts 9 seconds of bleed', 'Damage +30%', 'Firing speed +30%'],
  },
  'stock-sniper': {
    common: ['Damage +10%'],
    elite: ['Damage +20%', '+2 projectile or pellet per shot'],
    legendary: ['Damage +30%', '+3 projectile or pellet per shot', '+45 health on kill'],
  },
  'stock-spy': {
    common: ['inflicts 3 seconds of bleed'],
    elite: ['inflicts 6 seconds of bleed', 'Damage +20%'],
    legendary: ['inflicts 9 seconds of bleed', 'Damage +30%', 'Firing speed +30%'],
  },
  'credit-to-team': {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'Firing speed +20%'],
    legendary: ['Damage +30%', 'Firing speed +30%', '+45 health on kill'],
  },
  'screamin-eagles': {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'Firing speed +20%'],
    legendary: ['Damage +30%', 'Firing speed +30%', '+45 health on kill'],
  },
  ivan: {
    common: ['Firing speed +10%'],
    elite: ['Firing speed +20%', 'Clip size +50%'],
    legendary: ['Firing speed +30%', 'Clip size +75%', 'Damage +30%'],
  },
  'herr-doktor': {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'ÜberCharge rate +20%'],
    legendary: ['Damage +30%', 'ÜberCharge rate +30%', 'Firing speed +30%'],
  },
  chell: {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'Firing speed +20%'],
    legendary: ['Damage +30%', 'Firing speed +30%', '+45 health on kill'],
  },
  mentlegen: {
    common: ['Damage +10%'],
    elite: ['Damage +20%', 'Firing speed +20%'],
    legendary: ['Damage +30%', 'Firing speed +30%', 'Armor piercing +75%'],
  },
};
